# Assignment instruction

In this part of the assignment, you are asked to answer the following things

- Python basics
- NumPy (especially arrays)

Answer all questions. This assignment comprises 40 percent of the assignment grade.


# Python Basics (15 percent)

(1) How many elements in the list?

In [ ]:
int_list = [1102,  312, 1031,  947,    6,  940,  744,   38, 1659, 1982, 1510,
        152, 1964,  522,  665,   19,  218,  453, 1946, 1261, 1455, 1915,
       1152, 1182,  847,   61, 1287,  908, 1155,  768, 1743, 1002, 1522,
        220, 1495, 1923,  689,  397, 1149, 1035,  974,  985, 1759, 1442,
       1441, 1278, 1672,  605,  481,  377, 1207,  763,  691, 1953, 1214,
        834, 1841, 1905, 1585, 1834, 1716, 1610,  430, 1358,   95,   42,
       1584,  303,  859,  474,  210,   46, 1492, 1588, 1828, 1007, 1047,
        325,  476,  666,  762, 1866, 1241, 1343,  123, 1715, 1396,  138,
       1113, 1091, 1469, 1147, 1437, 1794,  482, 1213,  201,  165,  452,
       1095, 1378,  750, 1857, 1026,  872,  796,  308,  656, 1450,  376,
       1503,  409, 1737,   66,  802, 1097,  772,  969,  258, 1269,  761,
       1474, 1985,  478, 1588,  163,  815,  220, 1956, 1526, 1394, 1049,
        494,  145, 1842, 1344,  851, 1964, 1578,  548, 1336,  829, 1673,
        464,  803, 1967, 1152, 1218, 1769, 1078, 1765, 1883, 1896, 1125,
        857, 1623,  390, 1545,  574, 1226, 1971, 1995,  608, 1137, 1052,
       1785,  782,  705, 1760, 1441, 1537, 1055,  350,  144, 1679, 1998,
        929, 1510,  289, 1044, 1353,   28, 1431,  199,  221, 1086,  909,
        701,  699,  772, 1323,  807, 1029,  845, 1591,  222,  453, 1166,
        314,  982,  119, 1591, 1223, 1385,  579,  151, 1244,  113,  821,
        575,  398, 1357, 1410,  680, 1741,  322, 1685, 1457, 1425,  160,
       1158, 1377,  148, 1828, 1155, 1942, 1640,  716, 1599, 1745, 1866,
       1642,  212,  598, 1765,  263,  477,   93, 1724,   71, 1645, 1386,
       1791,  720,  331,  150, 1763, 1420, 1980, 1308,  464, 1180,  371,
       1920,  972,  274,  849,  959,  847, 1225,  798, 1749,  615, 1466,
       1523, 1385, 1389, 1243, 1148,  744, 1749,  495, 1520,  225,  682,
        398,   80,  199,  848, 1353, 1978,  605,  860,   93, 1423,  802,
        867,  848,  672,  802,  944, 1555,  106,  813, 1872,  675, 1469,
       1918,  972,  630,  296,  910,   85,  422,  678, 1437, 1929, 1982,
       1103, 1255, 1459, 1250,  125,  639,  637, 1565,  563,  329, 1654,
        405,  862,  683,  545,  172,  321,  479,  690,  193, 1053, 1103,
        567, 1762, 1615, 1271, 1807,  741, 1911, 1184, 1149, 1433,  985,
       1749, 1737,  450, 1054, 1622,  709, 1155, 1917, 1626,  550, 1377,
        459,  892, 1236,  871, 1880, 1131, 1463,   31,  223, 1921,   54,
       1898, 1864, 1261, 1931,  342,  488, 1362, 1947,  474, 1405,  601,
       1774,  794,  558, 1872,  801,  747,   71,  702,  403, 1787]

(2) Split the following string by word and create a list

In [ ]:
string = "A driverless truck is ready to start earning a living"

(3) For the python list below, run a loop where the number will be printed out when it is greater than 15. The output should look like:
```
17
18
17
18
18
18
16
17
16
```

In [ ]:
list_x = [ 0,  4, 17, 15, 10, 13,  7, 15, 13, 18,  3,  8, 17,  3,  4, 18, 15,
        0, 13, 10, 18, 18,  9, 11,  7, 16,  8,  8, 17, 10,  1,  1, 13,  7,
       15, 11,  2,  0, 16, 15,  0,  4,  2,  0,  4, 15, 14,  7, 14,  1]

# NumPy (25 percent)

In [ ]:
import numpy as np

## Array construction

Construct following NumPy arrays (without using `array()` method)

- one dimensional arrays:
    1. a sequece of integers from `-10` to `10`
    2. 10 random numbers drawn from uniform distribution 
    3. a sequence of integers from `23` to `0` (some arithmetic operations would be necessary)
- two dimensional arrays:
    1. 5 x 4 random array drawn from normal distribution
    2. 2 x 7 array of zeros
    3. 3 x 3 array of 7s, like this (some arithmetic operations would be necessary): 
      ```
      [[7. 7. 7.]
       [7. 7. 7.]
       [7. 7. 7.]]
      ```


## Array indexing and selection

### One dimension



#### From the array below, crate a replicating matrix

In [ ]:
arr_1d = np.arange(1, 16)

(1) `array([1, 2, 3, 4, 5, 6, 7])`

(2) `array([13, 14, 15])`

#### Do the following 

1. Set the seed to `208320`
2. Construct an array with 20 random numbers from normal distribution
3. Select positive elements from the array

### Two dimension


#### From the array below, crate a replicating matrix

In [ ]:
arr_2d = np.arange(31, 61).reshape(5, 6)

(1) 
```
array([[31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48]])
```

(2) 
```
array([[39, 40, 41],
       [45, 46, 47],
       [51, 52, 53]])
```

(3)
```
array([[43, 47],
      [55, 59]])
```

## Array operations

For the two dimensional array below, carry out the following operations

In [ ]:
arr_op = np.array([[63, 14, 95, 12, 37, 97, 51],
                  [29,  4, 69, 13, 74, 74, 32],
                  [14, 63, 83, 52, 16, 86, 78],
                  [75, 87,  2,  8, 83,  8, 32],
                  [99,  1, 66, 12, 36, 18, 76],
                  [45, 81, 23, 54, 38, 26, 30],
                  [67, 58, 79, 31, 52, 19, 76],
                  [82, 28, 34, 66, 67, 45, 32]])

(1) calculate the sum of the entire array

(2) calculate the mean of each row

(3) calculate the standard deviaiton of each column